x-logging:
  &logging
  driver: loki # shipping stdout to loki. In k8s, we can use fluentbit|promtail instead
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    loki-batch-size: 1048576
    loki-min-backoff: 1s
services:
  app:
    logging: *logging
    image: app
    ports:
      - "8080:8080"
    environment:
      - OTLP_ENDPOINT=tempo:4317
  collector:
    # collect span for tracing
    image: otel/opentelemetry-collector:latest
    container_name: collector
    hostname: collector
    command: [ "--config=/etc/otc-collector.yaml" ]
    volumes:
      - ./collector.yaml:/etc/otc-collector.yaml
    ports:
      - "5555:5555"

  tempo:
    image: grafana/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
    volumes:
      - ./tempo-local.yaml:/etc/tempo/config.yml
    command: [ "--config.file=/etc/tempo/config.yml" ]

  loki:
    image: grafana/loki:latest
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -table-manager.retention-period=1d
      - -table-manager.retention-deletes-enabled=true
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/ds.yml
