networks:
  grafana:
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/ds.yml

  agent:
    image: grafana/agent
    command:
      [
        "-config.file=/etc/agent/config.yml",
        "-metrics.wal-directory=/tmp/agent/wal"
      ]
    volumes:
      - ./agent-config.yml:/etc/agent/config.yml
      - /var/run/docker.sock:/var/run/docker.sock

  tempo:
    image: grafana/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
    volumes:
      - ./tempo-local.yaml:/etc/tempo/config.yml
    command: [ "--config.file=/etc/tempo/config.yml" ]

  app:
    image: app
    ports:
      - "8080:8080"
    environment:
      - OTLP_ENDPOINT=agent:4317
